=== Rill94/Lab1s1/out/artifacts/Lab1s1_war_exploded/WEB-INF/classes/xml/university.dtd
<!ELEMENT university (faculty+)>
<!ELEMENT faculty (id, name, head_of_faculty, chair+)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT head_of_faculty (id, first_name, mid_name, last_name)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT mid_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ATTLIST head_of_faculty %contacts;>
<!ATTLIST faculty image ENTITY #REQUIRED>
<!ENTITY facultyimage SYSTEM "../web/images/fit.gif" NDATA gif>

<!ELEMENT chair (id, name, head_of_chair, speciality+, lecturer+)>
<!ATTLIST chair orders IDREFS #IMPLIED>

<!ELEMENT head_of_chair (id, first_name, mid_name, last_name)>
<!ATTLIST head_of_chair %contacts;>

<!ELEMENT speciality (id, name, group+)

<!ELEMENT group (id, name, course, student)>
<!ELEMENT course (#PCDATA)>
<!ATTLIST group type (baccalaureate | magistracy) "baccalaureate"
          group group_order ID #REQUIRED>

<!ELEMENT student (id, first_name, mid_name, last_name, birth_date)>
<!ELEMENT birth_date (#PCDATA)>
<!ATTLIST student passport ID #REQUIRED
                  %contacts;>


<!ELEMENT lecturer (id, first_name, mid_name, last_name, position, degree?)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT degree (#PCDATA)>
<!ATTLIST lecturer %contacts;>

<!ENTITY % contacts "phoneNumber CDATA #REQUIRED
             eMail CDATA #REQUIRED">
<!NOTATION jpeg SYSTEM "image/jpeg">
<!NOTATION gif SYSTEM "image/gif">

=== Rill94/Lab1s1/out/artifacts/Lab1s1_war_exploded/WEB-INF/classes/xml/university.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE university SYSTEM "/Users/cake4rill/IdeaProjects/Lab1s1/src/xml/university.dtd">
<university>
  <faculty image="facultyimage">
    <id>1</id>
    <name>ФИТ</name>
    <head_of_faculty
      phoneNumber="89288468294"
      eMail="someaddress@gmail.com">
      <id>1</id>
      <first_name>Анатолий</first_name>
      <mid_name>Александрович</mid_name>
      <last_name>Галкин</last_name>
    </head_of_faculty>
    <chair>
      <id>1</id>
      <name>ИСПИ</name>
      <head_of_chair
        phoneNumber="89288468294"
        eMail="someaddress@gmail.com">
        <id>1</id>
        <first_name>Илья</first_name>
        <mid_name>Евгеньевич</mid_name>
        <last_name>Жигалов</last_name>
      </head_of_chair>
      <speciality>
        <id>1</id>
        <name>Информационные системы и технологии</name>
        <group type="baccalaureate">
          <id>1</id>
          <name>ИСТ-115</name>
          <course>1</course>
          <student passport="1134 537860" phoneNumber="89288468294" eMail="annamakarova@gmail.com">
            <id>1</id>
            <first_name>Анна</first_name>
            <mid_name>Сергеевна</mid_name>
            <last_name>Макарова</last_name>
            <birth_date>1997-11-08</birth_date>
          </student>
        </group>
        <group type="magistracy">
          <id>2</id>
          <name>ИСмм-214</name>
          <course>1</course>
          <student passport="1184 537860" phoneNumber="89288468294" eMail="ivanov@gmail.com">
            <id>2</id>
            <first_name>Дмитрий</first_name>
            <mid_name>Викторович</mid_name>
            <last_name>Иванов</last_name>
            <birth_date>1993-11-08</birth_date>
          </student>
        </group>
      </speciality>
      <speciality>
        <id>2</id>
        <name>Программная инженерия</name>
        <group type="baccalaureate">
          <id>3</id>
          <name>ПРИ-115</name>
          <course>1</course>
          <student passport="1234 567890" phoneNumber="89288468294" eMail="ivanpupkin@gmail.com">
            <id>3</id>
            <first_name>Иван</first_name>
            <mid_name>Васильевич</mid_name>
            <last_name>Пупкин</last_name>
            <birth_date>1998-10-05</birth_date>
          </student>
          <student passport="1214 567390" phoneNumber="89288468294" eMail="alexsidorov@gmail.com">
            <id>4</id>
            <first_name>Александр</first_name>
            <mid_name>Николаевич</mid_name>
            <last_name>Сидоров</last_name>
            <birth_date>1998-01-11</birth_date>
          </student>
        </group>
        <group type="magistracy">
          <id>4</id>
          <name>ПРИм-114</name>
          <course>1</course>
          <student passport="1234 537890" phoneNumber="89288468294" eMail="volkova@gmail.com">
            <id>5</id>
            <first_name>Мария</first_name>
            <mid_name>Александровна</mid_name>
            <last_name>Волкова</last_name>
            <birth_date>1992-12-08</birth_date>
          </student>
        </group>
      </speciality>
      <lecturer phoneNumber="89288468294" eMail="someaddress@gmail.com">
        <id>1</id>
        <first_name>Алексей</first_name>
        <mid_name>Владимирович</mid_name>
        <last_name>Костров</last_name>
        <position>Профессор</position>
        <degree>д.т.н.</degree>
      </lecturer>
      <lecturer phoneNumber="89288468294" eMail="someaddress@gmail.com">
        <id>2</id>
        <first_name>Руслан</first_name>
        <mid_name>Ильич</mid_name>
        <last_name>Макаров</last_name>
        <position>Профессор</position>
        <degree>д.т.н.</degree>
      </lecturer>
    </chair>

  </faculty>
</university>
